name: Validate Tag Build

on:
  push:
    tags:
      - "*"

jobs:
  build-and-validate-dist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: Set up Python 3.11
        uses: actions/setup-python@3542bca2639a428e1796aaa6a2ffef0c0f575566 # v3
        with:
          python-version: "3.11"
      - name: Install build dependencies
        run: python3 -m pip install --upgrade setuptools wheel build
      - name: Install Deno
        uses: denoland/setup-deno@e95548e56dfa95d4e1a28d6f422fafe75c4c26fb # v2.0.3
        with:
          deno-version: v2.7.7
      - name: Build distribution
        run: python3 -m build
      - name: Create test environment
        run: python -m venv test_before_dist
      - name: Validate built wheel against minimal suite
        run: |
          source test_before_dist/bin/activate
          pip install dist/*.whl pytest
          pytest tests/minimal -vv
          deactivate
